### ISSUE TITLE
Measurement integration and K8s correctness tests intermittently failing with reach ratio error

### ISSUE THREAD

**Issue by SanjayVas** [world-federation-of-advertisers/cross-media-measurement#1867]
Possibly introduced in #1860.

Sample stack trace:

```
java.lang.IllegalArgumentException: Reach ratio must be greater than or equal to 0 and less than or equal to 1, but got 1.0000000000000002.
    at org.wfanet.measurement.measurementconsumer.stats.LiquidLegions.varianceOfNumberOfNonDestroyedRegistersPerFrequency(LiquidLegions.kt:269)
    at org.wfanet.measurement.measurementconsumer.stats.LiquidLegions.liquidLegionsFrequencyRelativeVariance(LiquidLegions.kt:341)
    at org.wfanet.measurement.measurementconsumer.stats.VariancesImpl$constructLiquidLegionsV2FrequencyRelativeVariance$2.invoke(Variances.kt:375)
    at org.wfanet.measurement.measurementconsumer.stats.VariancesImpl$constructLiquidLegionsV2FrequencyRelativeVariance$2.invoke(Variances.kt:374)
    at org.wfanet.measurement.measurementconsumer.stats.VariancesImpl.frequencyVariance(Variances.kt:466)
    at org.wfanet.measurement.measurementconsumer.stats.VariancesImpl.computeLiquidLegionsV2Variance(Variances.kt:351)
    at org.wfanet.measurement.measurementconsumer.stats.VariancesImpl.computeMeasurementVariance(Variances.kt:840)
    at org.wfanet.measurement.loadtest.measurementconsumer.MeasurementConsumerSimulator.computeRelativeFrequencyTolerance(MeasurementConsumerSimulator.kt:648)
```

**Comment by SanjayVas** [comment]
Fixed by #1868
