### ISSUE TITLE
Kingdom data server running out of heap space

### ISSUE THREAD

**Issue by SanjayVas** [world-federation-of-advertisers/cross-media-measurement#690]
This may indicate a memory leak, as the Kingdom data server doesn't handle large payloads. This persisted even after increasing container memory to 512MiB and increasing the heap percentage to 40.

Sample traces:

```
com.google.cloud.spanner.SpannerException: UNKNOWN: Java heap space
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:291)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:297)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:61)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:181)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:110)
	at com.google.cloud.spanner.SpannerExceptionFactory.asSpannerException(SpannerExceptionFactory.java:100)
	at com.google.cloud.spanner.AbstractResultSet$GrpcResultSet.next(AbstractResultSet.java:137)
	at com.google.cloud.spanner.ForwardingResultSet.next(ForwardingResultSet.java:54)
	at com.google.cloud.spanner.SessionPool$AutoClosingReadContext$1.internalNext(SessionPool.java:273)
	at com.google.cloud.spanner.SessionPool$AutoClosingReadContext$1.next(SessionPool.java:253)
	at com.google.cloud.spanner.AsyncResultSetImpl$ProduceRowsCallable.call(AsyncResultSetImpl.java:340)
	at com.google.cloud.spanner.AsyncResultSetImpl$ProduceRowsCallable.call(AsyncResultSetImpl.java:334)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

```
java.lang.OutOfMemoryError: Java heap space
	at com.google.protobuf.UnknownFieldSet$Builder.<init>(UnknownFieldSet.java:308)
	at com.google.protobuf.UnknownFieldSet$Builder.create(UnknownFieldSet.java:311)
	at com.google.protobuf.UnknownFieldSet$Builder.access$000(UnknownFieldSet.java:304)
	at com.google.protobuf.UnknownFieldSet.newBuilder(UnknownFieldSet.java:71)
	at com.google.protobuf.Value.<init>(Value.java:50)
	at com.google.protobuf.Value.<init>(Value.java:17)
	at com.google.protobuf.Value$1.parsePartialFrom(Value.java:1635)
	at com.google.protobuf.Value$1.parsePartialFrom(Value.java:1629)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
	at com.google.protobuf.ListValue.<init>(ListValue.java:64)
	at com.google.protobuf.ListValue.<init>(ListValue.java:14)
	at com.google.protobuf.ListValue$1.parsePartialFrom(ListValue.java:855)
	at com.google.protobuf.ListValue$1.parsePartialFrom(ListValue.java:849)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
	at com.google.protobuf.Value.<init>(Value.java:101)
	at com.google.protobuf.Value.<init>(Value.java:17)
	at com.google.protobuf.Value$1.parsePartialFrom(Value.java:1635)
	at com.google.protobuf.Value$1.parsePartialFrom(Value.java:1629)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
	at com.google.protobuf.ListValue.<init>(ListValue.java:64)
	at com.google.protobuf.ListValue.<init>(ListValue.java:14)
	at com.google.protobuf.ListValue$1.parsePartialFrom(ListValue.java:855)
	at com.google.protobuf.ListValue$1.parsePartialFrom(ListValue.java:849)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
	at com.google.protobuf.Value.<init>(Value.java:101)
	at com.google.protobuf.Value.<init>(Value.java:17)
	at com.google.protobuf.Value$1.parsePartialFrom(Value.java:1635)
	at com.google.protobuf.Value$1.parsePartialFrom(Value.java:1629)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:889)
	at com.google.protobuf.ListValue.<init>(ListValue.java:64)
	at com.google.protobuf.ListValue.<init>(ListValue.java:14)
	at com.google.protobuf.ListValue$1.parsePartialFrom(ListValue.java:855)
```

**Comment by SanjayVas** [comment]
Noticed in logs right before this:

```
Sep 15, 2022 4:08:42 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
```

**Comment by SanjayVas** [comment]
This might be related to world-federation-of-advertisers/common-jvm#163. From heap analysis tool:

```
Details of biggest items:

43.8% size 86.30MiB     java.lang.Thread
    Heap Retainer Tree
      Name                                                                                                    Deep Size  Shallow Size
      java.lang.Thread                                                                                         86.30MiB          112B
        com.google.cloud.spanner.SessionPool$AutoClosingReadContext$AutoClosingReadContextAsyncResultSetImpl   86.29MiB           88B
          java.util.concurrent.LinkedBlockingDeque                                                             74.83MiB           40B
            java.util.concurrent.LinkedBlockingDeque$Node                                                       9.35MiB           24B
            java.util.concurrent.LinkedBlockingDeque$Node                                                       9.35MiB           24B
            java.util.concurrent.LinkedBlockingDeque$Node                                                       9.35MiB           24B
            java.util.concurrent.LinkedBlockingDeque$Node                                                       9.35MiB           24B
            java.util.concurrent.LinkedBlockingDeque$Node                                                       9.35MiB           24B
            java.util.concurrent.LinkedBlockingDeque$Node                                                       9.35MiB           24B
            ... and 6 more, totaling                                                                           18.71MiB
          com.google.cloud.spanner.AbstractResultSet$GrpcStruct                                                 9.35MiB           24B
          ... and 58 more, totaling                                                                             2.11MiB
        java.lang.ThreadLocal$ThreadLocalMap                                                                    1.79KiB           24B
        ... and 19 more, totaling                                                                               3.03KiB
```

My theory is that the AutoClosingReadContext is not properly detecting the condition that should close it. Its internal AutoClosingReadContextAsyncResultSetImpl adds a listener to decrement the current operation count, where the auto-close happens when that count hits 0. From the documentation for AsyncReadContext.addListener:

> Adds a listener that will be called when no more rows will be read from the underlying ResultSet, either because all rows have been read, or because AsyncResultSet.ReadyCallback.cursorReady(AsyncResultSet) returned AsyncResultSet.CallbackResponse.DONE.

This means that the listener will not be hit if we cancel out before reading all the results without the callback returning `AsyncResultSet.CallbackResponse.DONE`, and not necessarily just by the AsyncResultSet being closed. I'm going to test out preventing coroutine cancellation there.

**Comment by SanjayVas** [comment]
Another theory is that too many items are getting queued up in the async thread pool executor, but I think that may be a symptom rather than the cause.

**Comment by SanjayVas** [comment]
> This means that the listener will not be hit if we cancel out before reading all the results without the callback returning AsyncResultSet.CallbackResponse.DONE, and not necessarily just by the AsyncResultSet being closed. I'm going to test out preventing coroutine cancellation there.

This may have indeed be it. Overall memory usage reported by K8s had grown to 423MiB before running out of heap space, and it tended to climb up near that level relatively quickly. With three parallel MC simulators running, it's currently still only at 279MiB.

**Comment by SanjayVas** [comment]
I believe this is fixed by the current version of https://github.com/world-federation-of-advertisers/common-jvm/pull/163.
