### ISSUE TITLE
Reporting CLI: Error when filter isn't specified to `event-groups list` command

### ISSUE THREAD

**Issue by SanjayVas** [world-federation-of-advertisers/cross-media-measurement#739]
The `--filter` option is not required, but an exception is thrown when it's not set. It's incorrectly defined as a `lateinit` property, which implies it will always eventually be set.

Stack trace:
```
kotlin.UninitializedPropertyAccessException: lateinit property celFilter has not been initialized
        at org.wfanet.measurement.reporting.service.api.v1alpha.tools.ListEventGroups.run(Reporting.kt:433)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at org.wfanet.measurement.common.CommandLinesKt.commandLineMain(CommandLines.kt:40)
        at org.wfanet.measurement.reporting.service.api.v1alpha.tools.ReportingKt.main(Reporting.kt:497)
```

**Comment by renjiezh** [comment]
Thanks for catching that.
The fix: https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/740
