### ISSUE TITLE
getEventGroup returns key mismatch error

### ISSUE THREAD

**Issue by mariolamassaavedra** [world-federation-of-advertisers/cross-media-measurement#760]
- When calling the getEventGroup method an error is returned highlight that there is no matching private key. We have used Halo's testing TINK files to encrypt the metadata and configured them within the reporting server to be able to decrypt the eventGroups
- When trying to validate in Halo's dev environment we get an error as well

**Comment by SanjayVas** [comment]
Looks like this is talking about the Report API. If the error is "Public key does not have corresponding private key", then that means that no matching private key was found in the encryption key store. In the dev configuration, this comes from `encryption_key_pair_config.textproto` in the `config-files` ConfigMap.

Are you sure that the config file has an entry for the MC encryption key that was used to encrypt that EventGroup metadata? If using the Halo dev environment, the file has the following contents:

```textproto
# proto-file: wfa/measurement/config/reporting/encryption_key_pair_config.proto
# proto-message: EncryptionKeyPairConfig
principal_key_pairs {
  principal: "measurementConsumers/VCTqwV_vFXw"
  key_pairs {
    public_key_file: "mc_enc_public.tink"
    private_key_file: "mc_enc_private.tink"
  }
}
```

This means that the `data` field inside of the `measurement_consumer_public_key` field in the EventGroup must contain the contents of `mc_enc_public.tink`.

**Comment by SanjayVas** [comment]
Note that this is assuming that metadata was indeed specified for the EventGroup in question. There's a separate pending issue where the Reporting server attempts to decrypt EventGroup metadata even when it's not specified. See #752.

**Comment by SanjayVas** [comment]
I don't think this is caused by #738, as that's specifically an issue with metadata not being set. You stated that you're getting this when metadata is set.

I'm able to reproduce this error with the resource name you provided, but I still can't tell if it's expected as I don't know which key was used. The dev environment configuration only has one key pair in its `encryption_key_pair_config.textproto`: the checked-in `mc_enc_public.key` and `mc_enc_private.key`. This means that the call will fail unless _all_ EventGroups for that DataProvider in the dev environment used that public key.

**Comment by SanjayVas** [comment]
I ran a query in the dev Kingdom and found that the only EventGroup defined for `dataProviders/R180F6AQ584` does not have its `encrypted_metadata` field set, so the RPC above is expected to fail until #738 is fixed.

Do you have an example where this is failing when `encrypted_metadata` is set?

**Comment by mariolamassaavedra** [comment]
I do but is in our environment, this time it seems the error changed. Here's the details:

We redeployed the the entire platform using commit  d85919b12bc389f57797ecb7a06921fbe69371f0, wiped DBs, got new MC and EDP ids. We created 2 event groups with encrypted metadata. The metadata was encrypted using the [tink file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/k8s/testing/secretfiles/mc_enc_public.tink) form Halo's repo (see the E.Gs at the bottom). 

The associated private key is configured in the reporting server so decryption can occur. I can see the kingdom responding correctly but the reporting server is returning "UNKOWN" with the following error:

java.security.GeneralSecurityException: decryption failed at com.google.crypto.tink.hybrid.HybridDecryptWrapper$WrappedHybridDecrypt.decrypt(HybridDecryptWrapper.java:73) at org.wfanet.measurement.common.crypto.tink.TinkPrivateKeyHandle.hybridDecrypt(KeyHandle.kt:77) at org.wfanet.measurement.common.crypto.PrivateKeyHandle$DefaultImpls.hybridDecrypt$default(KeyHandle.kt:28) at org.wfanet.measurement.consent.client.measurementconsumer.MeasurementConsumerClientKt.decryptMetadata(MeasurementConsumerClient.kt:128) at org.wfanet.measurement.reporting.service.api.v1alpha.EventGroupsService.listEventGroups(EventGroupsService.kt:94) at org.wfanet.measurement.reporting.service.api.v1alpha.EventGroupsService$listEventGroups$1.invokeSuspend(EventGroupsService.kt) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)


{

  "eventGroups": [

    {

      "name": "dataProviders/MNstouxIrrI/eventGroups/C8ZbWOzPJfE",

      "measurementConsumer": "measurementConsumers/Pk21bxO3Uxc",

      "measurementConsumerCertificate": "measurementConsumers/Pk21bxO3Uxc/certificates/Gpl9qhO3U4g",

      "measurementConsumerPublicKey": {

        "data": "CAES5QEIrfyPlQUS3AEKzwEKPXR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmNyeXB0by50aW5rLkVjaWVzQWVhZEhrZGZQdWJsaWNLZXkSiwESRAoECAIQAxI6EjgKMHR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmNyeXB0by50aW5rLkFlc0djbUtleRICEBAYARgBGiEA2VOaFS7y+xGQvC2VydELNZValk7ASE8EXHny7b0tOX4iIC1a/MlmcWmzimHAUyPjtZfuRLqtlS6qUdkLj8/eb15bGAMQARit/I+VBSAB",

        "signature": "MEUCIQDP7cgMqAuP3va5QRbLDatJe69yVpg+H4S5EKYMR8X4aQIgHxH5vAfvwFVSfS9nvvmzKF99o5mgiDWjBwPyihFeWGk="

      },

      "eventGroupReferenceId": "TestEvent1"

    },

    {

      "name": "dataProviders/MNstouxIrrI/eventGroups/KN2jfuzPYw8",

      "measurementConsumer": "measurementConsumers/Pk21bxO3Uxc",

      "measurementConsumerCertificate": "measurementConsumers/Pk21bxO3Uxc/certificates/Gpl9qhO3U4g",

      "measurementConsumerPublicKey": {

        "data": "CAES5QEIrfyPlQUS3AEKzwEKPXR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmNyeXB0by50aW5rLkVjaWVzQWVhZEhrZGZQdWJsaWNLZXkSiwESRAoECAIQAxI6EjgKMHR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmNyeXB0by50aW5rLkFlc0djbUtleRICEBAYARgBGiEA2VOaFS7y+xGQvC2VydELNZValk7ASE8EXHny7b0tOX4iIC1a/MlmcWmzimHAUyPjtZfuRLqtlS6qUdkLj8/eb15bGAMQARit/I+VBSAB",

        "signature": "MEUCIQDP7cgMqAuP3va5QRbLDatJe69yVpg+H4S5EKYMR8X4aQIgHxH5vAfvwFVSfS9nvvmzKF99o5mgiDWjBwPyihFeWGk="

      },

      "eventGroupReferenceId": "TestEvent2"

    },

    {

      "name": "dataProviders/MNstouxIrrI/eventGroups/RPK29BOmsGI",

      "measurementConsumer": "measurementConsumers/Pk21bxO3Uxc",

      "eventGroupReferenceId": "001",

      "eventTemplates": [

        {

          "type": "wfa.measurement.api.v2alpha.event_templates.testing.TestVideoTemplate"

        }

      ]

    }

  ]

}

**Comment by SanjayVas** [comment]
I'm going ahead and marking this bug as a duplicate of #738 as we've been unable to reproduce outside of that condition. We should have a different bug filed for the decryption failure.

**Comment by SanjayVas** [comment]
Duplicate of #738

**Comment by mariolamassaavedra** [comment]
I thought this bug was for the decryption of meta data as https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/738 is about event groups with out metadata and my understanding is that 738 should not have any impact on the event groups that do have properly encrypted metadata. Are you saying that both issue have the same root cause?

**Comment by SanjayVas** [comment]
> I thought this bug was for the decryption of meta data as #738 is about event groups with out metadata

This bug is specifically about getting a key mismatch error. As far as we can tell, the only case where one would get that error is #738 hence filing this as duplicate.

> Are you saying that both issue have the same root cause?

I'm saying that all key mismatch errors we've seen so far appear to have been caused by #738. The decryption error you mentioned in https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/760#issuecomment-1341302750 has been split out to a new issue as #781 as it has nothing to do with a key mismatch error.
